server:
  port: 0
  servlet:
    context-path: /msvc-account
spring:
  application:
    name: msvc-account

  datasource:
    url: jdbc:mysql://localhost:3306/accountdb?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:configserver:http://localhost:8888/

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
